name: Cypress Tests
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          working-directory: frontend

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          if-no-files-found: error
          path: frontend

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      options: --user 1001
    needs: install
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: frontend

      - name: Cypress info
        run: npx cypress info

      - name: Node info
        run: node -v

      - name: __e Dir
        run: ls /__e

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v4
        with:
          start: npm run cypress run
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          parallel: true
        env:
          DEBUG: "cypress:server:args"


# name: e2e_test
# on: [push]
# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     container: cypress/browsers:node16.14.2-slim-chrome103-ff102
#     steps:
#       - name: checkout repository
#         uses: actions/checkout@v2
#       # cypress test run
#       - name: cypress run
#         uses: cypress-io/github-action@v2
#         with:
#           browser: chrome
#           headless: true
#         # cypress debug
#         # env:
#         #   DEBUG: 'cypress:*'

