name: Cypress Tests
on: [push]
jobs:
  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        containers: [base, advanced, ultimate]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: temp

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Npm install
        working-directory: temp/frontend
        run: npm install

      - name: Run Cypress
        working-directory: temp/frontend
        run: npm run cy:run -- --browser chrome --spec ./cypress/e2e/${{ matrix.containers }}
